### ISSUE TITLE
Increase Header Image Size

### ISSUE THREAD

**Issue by sakinshrestha** [wpnepal/wcktmnepal-2016#2]
I would prefer full width header image size at least supporting 1920px resolution 
![header-image](https://cloud.githubusercontent.com/assets/9452203/16755407/278c12fc-481c-11e6-8896-e0be7ca3150b.png)

**Comment by ernilambar** [comment]
Fixed in https://github.com/wpnepal/wcktmnepal-2016/commit/7234db36a2f7c7143a4f8aa7f00b1394137b057d
