### ISSUE TITLE
Styling: List items issue

### ISSUE THREAD

**Issue by sakinshrestha** [wpnepal/wcktmnepal-2016#4]
There is issue in list items at http://2016.kathmandu.wordcamp.org/code-of-conduct/. 
- Check in that the heading tags are below the order list
- Also there is no space above no. 4.

**Comment by ernilambar** [comment]
Fixed in https://github.com/wpnepal/wcktmnepal-2016/commit/3722e0e450ccc0ff140fcc9fe9550f82cb2bc364
