### ISSUE TITLE
Check image path and move to https

### ISSUE THREAD

**Issue by sakinshrestha** [wpnepal/wcktmnepal-2016#5]
- I still see few images as http path and it's causing issue to https. For example, banner image http://2016.kathmandu.wordcamp.org/files/2016/07/wcktm-main-banner.png in remove css.

**Comment by ernilambar** [comment]
Fixed in https://github.com/wpnepal/wcktmnepal-2016/commit/06c2c33cec4b8c16ec3521ce3ec9c98e979a8657
