### ISSUE TITLE
Attendees Design issue

### ISSUE THREAD

**Issue by sakinshrestha** [wpnepal/wcktmnepal-2016#6]
1. Can you change the layout to have image and text center and also let the image size come automatically and not controlled by css. Proposed design: 
   ![attendees-design](https://cloud.githubusercontent.com/assets/9452203/17620512/8ff00e40-60ac-11e6-82ea-7aa268db4323.png)
2. Resposnive design issue . There is overlapping of text in mobile version. So, can you make it like https://2016.europe.wordcamp.org/attendees/. See this screenshot of overlapping
   ![responsive-attendees-design-issue](https://cloud.githubusercontent.com/assets/9452203/17620545/da6d40c8-60ac-11e6-8ee3-0ad30245fd81.png).

**Comment by ernilambar** [comment]
Fixed now.
